<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LocalWP.Application\LocalWP.Application.csproj" />
    <ProjectReference Include="..\..\src\LocalWP.Domain\LocalWP.Domain.csproj" />
  </ItemGroup>
</Project>
